import type { SavedProject } from './storage';

export const starterProjects: SavedProject[] = [
  {
    id: 'heart-of-the-hemisphere',
    title: 'Heart of the Hemisphere',
    bookType: 'Children adventure',
    genre: 'Children adventure story',
    audience: 'Children and families interested in the cultures, landscapes, and people of the Americas',
    tone: 'Curious, kind, adventurous, hopeful',
    idea: 'A young protagonist discovers the Americas and learns that people across borders share common hopes, fears, and dreams.',
    length: 'Children book length',
    goal: 'Shape the journey into a warm, illustrated adventure',
    wordCount: 0,
    createdAt: new Date(2026, 5, 6).toISOString(),
    updatedAt: new Date(2026, 5, 6).toISOString(),
    blueprint: {
      title: 'Heart of the Hemisphere',
      promise:
        'A children adventure story about curiosity, kindness, cultural understanding, and finding a place in a vast shared world.',
      targetReader: 'Young readers who like discovery stories with heart, travel, and a sense of wonder.',
      chapters: [
        { title: 'The Map Opens', goal: 'Introduce the protagonist and the first pull toward the wider Americas.' },
        { title: 'Mountains, Rivers, Cities', goal: 'Turn landscapes into discoveries about people and belonging.' },
        { title: 'Different Homes, Familiar Hopes', goal: 'Show that communities can differ while sharing human needs.' },
        { title: 'The Kindness Test', goal: 'Give the protagonist a choice that proves what the journey has taught.' },
        { title: 'A Place In The Hemisphere', goal: 'Bring the lesson home without making the world feel smaller.' },
      ],
      milestones: [
        'Choose the protagonist name and home setting',
        'Pick the key places in the journey',
        'Draft the first three illustrated scenes',
        'Create a page-by-page children book outline',
      ],
      writingPlan: 'Write one short scene per session, focused on one place, one person, and one lesson.',
      firstQuest: 'Write the opening page where the protagonist first sees the map or hears the call to travel.',
      nextActions: ['Name the protagonist', 'Choose 8-12 journey stops', 'Draft the first illustrated scene'],
    },
  },
  {
    id: 'of-stones-and-stars',
    title: 'Of Stones and Stars',
    bookType: 'Fantasy novel',
    genre: 'Sweeping fantasy',
    audience: 'Fantasy readers who like ancient civilizations, celestial magic, and unlikely alliances',
    tone: 'Epic, mysterious, mythic, urgent',
    idea: 'Ancient monuments connect the physical world to celestial forces, and forgotten powers begin awakening.',
    length: 'Novel length',
    goal: 'Build the world, magic system, and first-act quest',
    wordCount: 0,
    createdAt: new Date(2026, 5, 6).toISOString(),
    updatedAt: new Date(2026, 5, 6).toISOString(),
    blueprint: {
      title: 'Of Stones and Stars',
      promise:
        'A fantasy novel where ancient monuments, celestial forces, and old rivalries collide as unlikely allies uncover a dangerous truth.',
      targetReader: 'Readers who want large-scale fantasy with mystery, ruins, magic, and political fracture.',
      chapters: [
        { title: 'The First Awakening', goal: 'Show the first monument reacting to the stars.' },
        { title: 'The Rival Houses', goal: 'Introduce the old divisions that make the discovery dangerous.' },
        { title: 'The Unlikely Company', goal: 'Bring together allies who should not trust each other.' },
        { title: 'The Star Mechanism', goal: 'Reveal the first rule connecting stones and celestial power.' },
        { title: 'The Old Lie', goal: 'Expose the historical truth that could restart a war.' },
      ],
      milestones: [
        'Define the monument system',
        'Name the central civilizations and rival factions',
        'Create the core cast of unlikely allies',
        'Outline the first act around the first awakening',
      ],
      writingPlan: 'Alternate worldbuilding sessions with scene drafting so the mythology stays attached to character choices.',
      firstQuest: 'Write the scene where the first stone monument changes under the night sky.',
      nextActions: ['Define the magic rules', 'Name the rival factions', 'Draft the first awakening scene'],
    },
  },
  {
    id: 'yachay-pacha',
    title: 'Yachay Pacha',
    bookType: 'Literary campus novel',
    genre: 'Institutional literary fiction',
    audience: 'Readers interested in education, identity, cultural preservation, innovation, and power',
    tone: 'Reflective, political, human, layered',
    idea: 'At a remote mountain institute, students, teachers, researchers, and local residents must decide whether knowledge serves power or humanity.',
    length: 'Novel length',
    goal: 'Build the ensemble and the institution at the center of the story',
    wordCount: 0,
    createdAt: new Date(2026, 5, 6).toISOString(),
    updatedAt: new Date(2026, 5, 6).toISOString(),
    blueprint: {
      title: 'Yachay Pacha',
      promise:
        'A layered novel about a mountain institute where knowledge, ambition, identity, and community collide under political pressure.',
      targetReader: 'Readers who like ensemble fiction, institutional tension, and stories about the ethics of knowledge.',
      chapters: [
        { title: 'The Institute Above The Valley', goal: 'Establish the school, the mountain setting, and the promise of knowledge.' },
        { title: 'Students Of Two Worlds', goal: 'Introduce the students caught between ambition and belonging.' },
        { title: 'The Discovery', goal: 'Reveal the hidden finding that changes the institution future.' },
        { title: 'Pressure From Below And Above', goal: 'Bring political, local, and personal pressures into conflict.' },
        { title: 'Wisdom Has A Cost', goal: 'Force the cast to choose what knowledge is for.' },
      ],
      milestones: [
        'Map the institute and surrounding community',
        'Create the ensemble cast by role and pressure',
        'Define the hidden discovery',
        'Outline the political threat to the institute',
      ],
      writingPlan: 'Build one character dossier, one institutional pressure, and one scene per writing session.',
      firstQuest: 'Write the arrival scene at the mountain institute from a student or local resident POV.',
      nextActions: ['Name the institute leaders', 'Define the hidden discovery', 'Draft the arrival scene'],
    },
  },
  {
    id: 'chronicles-of-the-veil-fractured-veil',
    title: 'Chronicles of the Veil: The Fractured Veil',
    bookType: 'Fantasy novel',
    genre: 'Portal / barrier fantasy',
    audience: 'Fantasy readers who like unstable realities, ancient secrets, and shifting alliances',
    tone: 'Mysterious, tense, magical, cinematic',
    idea: 'A mystical barrier called the Veil begins fracturing, returning forgotten creatures, ancient magic, and dangerous secrets.',
    length: 'Novel length',
    goal: 'Clarify the Veil mythology and the protagonist first conflict',
    wordCount: 0,
    createdAt: new Date(2026, 5, 6).toISOString(),
    updatedAt: new Date(2026, 5, 6).toISOString(),
    blueprint: {
      title: 'Chronicles of the Veil: The Fractured Veil',
      promise:
        'A fantasy story about a young protagonist caught between restoring a mystical barrier and tearing down the lie behind it.',
      targetReader: 'Readers who want magic, creatures, factions, ancient secrets, and a reality-bending central mystery.',
      chapters: [
        { title: 'The First Fracture', goal: 'Open with the Veil breaking in a visible, dangerous way.' },
        { title: 'What Came Through', goal: 'Introduce the forgotten creature or magic that proves the old stories were real.' },
        { title: 'The Restorers', goal: 'Show the faction that believes survival depends on sealing the Veil.' },
        { title: 'The Breakers', goal: 'Show the faction that believes the Veil was a prison or a lie.' },
        { title: 'The Creation Secret', goal: 'Reveal that both sides misunderstand why the Veil exists.' },
      ],
      milestones: [
        'Define what the Veil separates',
        'Create the protagonist and personal stake',
        'Name the two main factions',
        'Draft the first fracture scene',
      ],
      writingPlan: 'Write through the first fracture, then build the factions around what each side fears losing.',
      firstQuest: 'Write the exact moment the protagonist sees the Veil fracture for the first time.',
      nextActions: ['Define the Veil rules', 'Name the protagonist', 'Draft the first fracture scene'],
    },
  },
  {
    id: 'shattering-of-maps',
    title: 'The Shattering of Maps',
    bookType: 'Geopolitical fiction series',
    genre: 'Five-book geopolitical fiction',
    audience: 'Readers who like morally compromised insiders, institutional dysfunction, and human-scale geopolitics',
    tone: 'Dry, cruel, morally compromised, institutional',
    idea: 'Borders are redrawn by a resource grab dressed as humanitarian intervention, centered on Bolivia and the Salar de Uyuni lithium economy.',
    length: 'Five-book series',
    goal: 'Continue from the drafted Chapter One manuscript',
    wordCount: 2400,
    createdAt: new Date(2026, 5, 6).toISOString(),
    updatedAt: new Date(2026, 5, 6).toISOString(),
    blueprint: {
      title: 'The Shattering of Maps',
      promise:
        'A geopolitical fiction series about extraction, institutional failure, and the human cost of maps redrawn by outsiders.',
      targetReader:
        'Readers who want intelligence fiction with dry humor, compromised insiders, and geopolitics seen from the place being extracted from.',
      chapters: [
        {
          title: 'Santa Cruz',
          goal: 'Reopen Marco Halvorsen-Quispe as the burned-out analyst close enough to see the lie forming.',
        },
        {
          title: 'Brussels',
          goal: 'Position Solene Adeyemi-Bauer as the institutional outsider watching policy become cover.',
        },
        {
          title: 'Uyuni',
          goal: 'Anchor Bishop Tomas Mamani in the place that others keep turning into an asset.',
        },
        {
          title: 'The Humanitarian Frame',
          goal: 'Show the public story hardening while the private motives stay ugly.',
        },
        {
          title: 'The Redrawn Line',
          goal: 'Make the extraction visible through failure, compromise, and betrayal.',
        },
      ],
      milestones: [
        'Re-read and annotate the existing Chapter One draft',
        'Create a five-book series spine',
        'Draft Chapter Two from the strongest unresolved POV',
        'Build a character pressure map for Marco, Solene, and Bishop Mamani',
      ],
      writingPlan:
        'Spend the next three sessions converting the existing Chapter One into a series launch plan, then draft Chapter Two in focused 500-word quests.',
      firstQuest: 'Write a one-page continuation note: what does each POV know at the end of Chapter One?',
      nextActions: [
        'Import or paste the Chapter One manuscript into the editor',
        'Outline the five-book escalation arc',
        'Draft the next scene from the POV with the most immediate pressure',
      ],
    },
  },
  {
    id: 'suerte-companion-book',
    title: 'The SUERTE Companion Book',
    bookType: 'Lore book and bilingual story collection',
    genre: 'Art book / bilingual companion book',
    audience: 'Fans of the SUERTE loteria deck, bilingual readers, collectors, and families',
    tone: 'Playful, sharp, vivid, character-driven',
    idea: 'A companion title built from the 54 original SUERTE characters, turning the deck into lore, art, and short bilingual stories.',
    length: '54 character entries',
    goal: 'Turn the existing IP into the fastest finished book',
    wordCount: 0,
    createdAt: new Date(2026, 5, 6).toISOString(),
    updatedAt: new Date(2026, 5, 6).toISOString(),
    blueprint: {
      title: 'The SUERTE Companion Book',
      promise:
        'A lore-rich companion book that gives every SUERTE card a voice, backstory, visual identity, and bilingual story hook.',
      targetReader: 'People who already connect with the deck and readers discovering the world through its characters.',
      chapters: [
        {
          title: 'The Deck As A World',
          goal: 'Explain the rules, tone, and cultural engine of the SUERTE universe.',
        },
        {
          title: 'La Chancla',
          goal: 'Open with a character entry that proves the book can be funny, specific, and iconic.',
        },
        {
          title: 'El Taquero',
          goal: 'Use food, work, and ritual to ground the world in everyday mythology.',
        },
        {
          title: 'La Toxica',
          goal: 'Create a character spread that balances humor, attitude, and story potential.',
        },
        {
          title: 'El Tio Borracho',
          goal: 'Show how a familiar archetype can become a layered illustrated entry.',
        },
      ],
      milestones: [
        'Choose the final format: lore book, art book, bilingual story collection, or hybrid',
        'Create the repeatable template for one character spread',
        'Draft the first five character entries',
        'Batch the remaining 49 entries by theme',
      ],
      writingPlan:
        'Finish one character spread at a time. Each spread gets a title, visual note, English copy, Spanish copy, and one story hook.',
      firstQuest: 'Build the template for one SUERTE character spread using La Chancla.',
      nextActions: [
        'Pick the final book format',
        'Write the first La Chancla spread',
        'Group all 54 characters into sections',
      ],
    },
  },
];
